#!/bin/bash
# verify-v0.0.0-release.sh
#
# Post-dispatch verification helper for the v0.0.0 release (issue #453).
#
# Run this script AFTER dispatching .github/workflows/release.yml with
# version=v0.0.0 and ref=main and waiting for that workflow run to succeed.
#
# Usage:
#   WORKFLOW_RUN_URL="https://github.com/mfrancza/agentic-development-workflow/actions/runs/<run-id>" \
#   bash .github/scripts/verify-v0.0.0-release.sh
#
# The script checks all three artifacts listed in issue #453 and, when all
# pass, prints a pre-formatted summary comment ready to post on issue #451.
#
# Exit code 0 — all checks passed, summary printed.
# Exit code 1 — one or more checks failed; details printed to stderr.

set -euo pipefail

REPO="mfrancza/agentic-development-workflow"
VERSION="v0.0.0"
MAJOR_TAG="v0"
PARENT_ISSUE=451

WORKFLOW_RUN_URL="${WORKFLOW_RUN_URL:-}"

# ── helpers ────────────────────────────────────────────────────────────────

pass() { echo "  ✅ $*"; }
fail() { echo "  ❌ $*" >&2; }
info() { echo "  ℹ️  $*"; }

# ── check 1: exact version tag ─────────────────────────────────────────────

echo ""
echo "=== Check 1: tag $VERSION exists on origin ==="
TAG_LINE_EXACT="$(git ls-remote --tags origin "refs/tags/${VERSION}" 2>/dev/null || true)"
if [[ -z "${TAG_LINE_EXACT}" ]]; then
  fail "refs/tags/${VERSION} not found on origin"
  CHECKS_FAILED=1
else
  EXACT_SHA="$(echo "${TAG_LINE_EXACT}" | awk '{print $1}')"
  pass "refs/tags/${VERSION} → ${EXACT_SHA}"
fi

# ── check 2: moving major tag, same SHA ────────────────────────────────────

echo ""
echo "=== Check 2: moving tag $MAJOR_TAG exists and points at the same SHA ==="
TAG_LINE_MAJOR="$(git ls-remote --tags origin "refs/tags/${MAJOR_TAG}" 2>/dev/null || true)"
if [[ -z "${TAG_LINE_MAJOR}" ]]; then
  fail "refs/tags/${MAJOR_TAG} not found on origin"
  CHECKS_FAILED=1
else
  MAJOR_SHA="$(echo "${TAG_LINE_MAJOR}" | awk '{print $1}')"
  if [[ "${MAJOR_SHA}" != "${EXACT_SHA:-}" ]]; then
    fail "refs/tags/${MAJOR_TAG} → ${MAJOR_SHA} (does NOT match ${VERSION} SHA ${EXACT_SHA:-<unknown>})"
    CHECKS_FAILED=1
  else
    pass "refs/tags/${MAJOR_TAG} → ${MAJOR_SHA} (matches ${VERSION})"
  fi
fi

# ── check 3: GitHub Release ─────────────────────────────────────────────────

echo ""
echo "=== Check 3: GitHub Release $VERSION exists, is latest, has notes ==="
RELEASE_JSON="$(gh api "/repos/${REPO}/releases/tags/${VERSION}" 2>/dev/null || true)"
if [[ -z "${RELEASE_JSON}" ]]; then
  fail "GitHub Release ${VERSION} not found"
  CHECKS_FAILED=1
else
  IS_LATEST="$(echo "${RELEASE_JSON}" | jq -r '.make_latest // "unknown"')"
  HAS_BODY="$(echo "${RELEASE_JSON}" | jq -r 'if (.body // "" | length) > 0 then "yes" else "no" end')"
  RELEASE_URL="$(echo "${RELEASE_JSON}" | jq -r '.html_url')"

  if [[ "${IS_LATEST}" != "true" ]]; then
    fail "make_latest field: ${IS_LATEST} — release is not marked latest (verify in the UI)"
    CHECKS_FAILED=1
  else
    pass "Release is marked latest"
  fi

  if [[ "${HAS_BODY}" == "no" ]]; then
    fail "Release body is empty — autogenerated notes may not have been applied"
    CHECKS_FAILED=1
  else
    pass "Release has autogenerated notes"
  fi

  pass "Release URL: ${RELEASE_URL}"
fi

# ── summary ─────────────────────────────────────────────────────────────────

echo ""
if [[ "${CHECKS_FAILED:-0}" == "1" ]]; then
  echo "One or more checks FAILED. Resolve the issues above before posting the summary comment." >&2
  exit 1
fi

TAGGED_SHA="${EXACT_SHA:-<sha>}"
RELEASE_URL_OUT="${RELEASE_URL:-https://github.com/${REPO}/releases/tag/${VERSION}}"
RUN_URL="${WORKFLOW_RUN_URL:-<paste workflow run URL here>}"

echo "=== All checks passed. Summary comment for issue #${PARENT_ISSUE}: ==="
echo ""
echo "---"
cat <<EOF

## v0.0.0 Release — Dispatch and Verification Summary

Task 2 of the initial-release design (issue #453) is complete.

### Workflow run

- **release.yml run:** ${RUN_URL}

### Tagged SHA

Both tags point at the same commit:

| Tag | SHA |
|-----|-----|
| \`v0.0.0\` | \`${TAGGED_SHA}\` |
| \`v0\` | \`${TAGGED_SHA}\` |

### GitHub Release

- **Release URL:** ${RELEASE_URL_OUT}
- Marked as latest release: $([ "${IS_LATEST}" = "true" ] && echo "✅" || echo "⚠️ ${IS_LATEST} — verify in UI")
- Autogenerated release notes: ✅

### Artifact verification (issue #453 checklist)

- [x] \`git ls-remote --tags origin refs/tags/v0.0.0\` → exactly one line
- [x] \`git ls-remote --tags origin refs/tags/v0\` → exactly one line, same SHA as \`v0.0.0\`
- [x] GitHub Release \`v0.0.0\` exists, is latest, has autogenerated notes

**Next:** Task 3 (#454) — verify GHCR image publication and public pullability.
EOF
echo "---"
